export const EnumError = {
    ROUTING_ERROR:1,
    INVALID_TYPES_ERROR:2,
    DATABASE_ERROR:3,
    INVALID_LENGTH_ERROR:4,
    REPETED_VALUE_DB_ERROR:5,
}

export const EnumNameError = {
    INVALID_CREDENTIALS_CART:1,
    INVALID_CREDENTIALS_PRODUCTS:2,
    REPETED_VALUE:3
}